__author__ = 'SuSh'

from filecreation import *
from projectutils import *

def addUserMetadata(user):
     writeUserData("data.bin",user)

def writesubForumData(subForumData):
    writeSubforumdata("data.bin",subForumData)
    present_forum_name=subForumData.forumname
    present_subforum_id=subForumData.id
    getForumUpdated(present_forum_name,present_subforum_id)

def writeMessageData(messageData):
    writeMessagedata("data.bin",messageData)
    present_forumname=messageData.forumName
    present_subforum_name=messageData.subForumname
    present_message_id=messageData.id
    getSubForumUpdated(present_forumname,present_subforum_name,present_message_id,messageData)

def writereplyData(replydata):
    writeReplyData("data.bin",replydata)
    link1,count=getFirstSubforumId(replydata.forumname)
    link2,count1=getFirstMessageId(link1,count,replydata.subForumname)
    getRequiredMessageId(link2,count1,replydata.q_id,replydata.id,replydata)

def viewQuestions(subFObj):
    link1,count=getFirstSubforumId(subFObj.forumname)
    print "link1=",link1,"count=",count
    link2,count1=getFirstMessageId(link1,count,subFObj.name)
    q_idList=getQuestionIds(link2,count1)
    return q_idList

def viewReplies(msgObj):
    link1,count=getFirstSubforumId(msgObj.forumName)
    link2,count1=getFirstMessageId(link1,count,msgObj.subForumname)
    link3,count2=getFirstReplyId(link2,count1,msgObj.id)
    replyIdList=getReplies(link3,count2)
    print replyIdList

if __name__=="__main__":
    user1=User("amani","amani12","amani@gmail.com",[1992,8,04],datetime.date(2013,6,15))
    addUserMetadata(user1)
    i=0
    while i <50:
        subforum=SubForum("hashing","amani","Education")
        writesubForumData(subforum)
        i+=1
    while i<100:
        msg=Message("Education","hashing","amani",350,"Producing hash values for accessing data or for security. A hash value (or simply hash), also called a message digest, is a number generated from a string of text. The hash is substantially smaller than the text itself, and is generated by a formula in such a way that it is extremely unlikely that some other text will produce the same hash value.")
        writeMessageData(msg)
        i+=1
    while i<200:
        rep=Reply("Education","hashing",86230,"amani",20,"xxxxxxxxxxxxxxxx")
        writereplyData(rep)
        i+=1
    while i<300:
        subforum=SubForum("CricketScores","amani","Sports")
        writesubForumData(subforum)
        i+=1
    subF=SubForum("hashing","","Education")
    viewQuestions(subF)
    msgO=Message("Education","hashing","",0,"")
    viewReplies(msgO)